FreeTubeApp/yt-channel-info

- app/youtube-grabber.js
In getChannelPlaylistsMore(), there is no check on whether continuation data is available and therefore fails when there is no further continuation that can be obtained from the response (happens when you are fetching the last page of playlists).
> Check continuation in getChannelPlaylistsMore()

- README.md
- app/youtube-grabber.js
I needed this for a personal project, and thought why not contribute it to the main repository.
Anyways, this PR adds a boolean to the channel info for if the channel is verified, by looking at the returned json's badges and checking if there's one that says 'Verified'.
I looked at modifying the tests for this change, but it seems those are a bit out of date, so I didn't do that. I did update the README though.
> Add isVerified boolean to channel info

- app/youtube-grabber.js
This error appears, when requesting the last continuation. With this little fix it now works fine.
```
node_modules\yt-channel-info\app\youtube-grabber.js:160
nextContinuation = continuationItem[0].continuationItemRenderer.continuationEndpoint.continuationCommand.token
^
TypeError: Cannot read property 'continuationItemRenderer' of undefined
at Function.getChannelVideosMore (node_modules\yt-channel-info\app\youtube-grabber.js:160:46)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
The problem was that _continuationItem_ was not _undefined_, but an _empty array_.
> fixed error when requesting last continuation

- app/helper.js
Hi! 
I found this small bug using FreeTube (which is awesome by the way! 👏️).
The `viewCount` is parsed incorrectly when a live video has more than a thousand viewers.
I parsed the value from `viewCountText` instead of `shortViewCountText`.
> Fix viewCount for live videos

- app/fetchers/channel.js
- app/fetchers/playlist.js
- app/youtube-grabber.js
With the changes from Svallinn at https://github.com/FreeTubeApp/FreeTube/pull/1148 we also need the possibility to use these links as their new kind of user id can be linked as well, and the other two URLs cannot work with this id.
An example link looks the following:
https://www.youtube.com/c/thisisaviva
> /c/ Channel URL Support

- README.md
- app/youtube-grabber.js
There is [a bug in the latest version of FreeTube](https://github.com/FreeTubeApp/FreeTube/issues/1101)  that prevents some channels from properly loading. The underlying problem is that on channels with more than 12 related channels, there is an unhandled continuation token for getting more related channels.
This pull request revises `getChannelInfo()` to return just the first 12 related channels, along with the `relatedChannelsContinuation` if relevant. It additionally adds `getRelatedChannelsMore()` to get further related channels.
I tried my best to make the new functions consistent with the existing continuation code, though there is a difference in how I name some variables.  The other continuation functions, like `getChannelVideos()`, use `items` and `continuation` naming,  but …
> Add getRelatedChannelsMore() to fix error in getting channel info

- README.md
- app/fetchers/channel.js
- app/fetchers/playlist.js
- app/helper.js
- app/youtube-grabber.js
- package.json
---
Rework of the channel url request structure and new performance flag
---
The goals of the changes are the following:
- More compressed structure of channel URL request code
- Easier maintainability of network code
- Higher performance when newly provided flag is used
**More compressed structure of channel URL request code**
The code in the playlist.js and channel.js files have been reduced massively. The try and catch like testing of channelId URLs has been removed from the previous two and also from the YouTubeGrabber.js file. 
**Easier maintainability of network code**
For most of the functions, the function call to makeChannelRequest() has been moved into the helper class. So there are all URLs closely packed for easier maintainability. The functionality functions only provide the …
> Rework of the channel url request structure and new performance flag

- README.md
- app/helper.js
- package.json
I added a new field 'author' to the community posts, so it can be displayed which channel actually posted the post.
Additionally I now concatenate all strings of the post's text together instead of only using the first part if split.
Additionally added case for very rare shared posts, which only occurred on the YouTube Creator channel yet, but must be covered, else the module fails
> Added author field, fixed missing parts of the post's text.

- README.md
- app/youtube-grabber.js
Because Channel tags aren't something that is displayed to users on YouTube, I imagine it's more likely to change than other properties so I surrounded it in a try catch loop.
This is what the output looks like when running getChannelInfo on Linus Tech Tips
> add channel tags to channel info

- README.md
- app/helper.js
- app/youtube-grabber.js
**Relevant issue**
closes #33
**Description**
The functions `getChannelInfo` and `getChannelVideos` will now return the alert message given by a response as the sole property of the return object upon loading a non-existent (e.g., removed, banned) channel. Formerly, `getChannelInfo` threw a rejected Promise object with the response alert text, and `getChannelVideos` did not check for this case at all (thus, it annoyingly returned `TypeError: Cannot read property 'channelMetadataRenderer' of undefined`). The README is updated accordingly with the new usage of the aforementioned functions (as well as the commented-out `throw response.alert` which informs developers how to maintain the old error design flow).
This PR should now handle the common case of a deleted or banned channel (or …
> Returning an object instead of error on non-existing channels

- README.md
- app/helper.js
youtube stopped providing the url for "Play all" in the videos tab.
Getting the "Uploads" playlist from #55 will be the way to get a playlist of all videos from the channel.
> revert changes from #52

- README.md
- app/youtube-grabber.js
Extracts the following
- Channel Join Date
- Channel View Count
- Channel Location
Related issue: https://github.com/FreeTubeApp/FreeTube/issues/1357
I'm not sure if these stats can be hidden or not so I have not tested this method with a channel that has it hidden (as I am not aware of any/if it's possible)
I also think that the items from this method make sense as being a part of getChannelInfo but I decided not to do it because I imagine a lot of people won't use it and it would add an extra http request to YT
> Add getChannelStats method

- app/youtube-grabber.js
I had a channel with only primary links, causing the error:
debug TypeError: Cannot read property 'map' of undefined
debug at Function.getChannelInfo (///node_modules/yt-channel-info/app/youtube-grabber.js:40:68)
The structure of 'links' at that point was:
{
primaryLinks: [ { navigationEndpoint: [Object], icon: [Object], title: [Object] } ]
}
rather than:
{
primaryLinks: [ { navigationEndpoint: [Object], icon: [Object], title: [Object] } ],
secondaryLinks: [ { navigationEndpoint: [Object], icon: [Object], title: [Object] } ]
}
Not sure if you need to create empty secondaryLinks array instead at that point, but this fix works fine for me.
> Fix for channels with no secondary links

- app/fetchers/playlist.js
- app/helper.js
- app/youtube-grabber.js
> Fix issue with parsing data

- app/helper.js
Now parses multiImage community posts
> Add 'multiImage' community posts

- app/helper.js
- app/youtube-grabber.js
- package-lock.json
- package.json
Summary of Changes:
- Reduces the lines of codes to increase readability 
- Gets rid of querystring dependency
- Upgrades axios
- Displays test coverage when tests are ran
- Removed unused methods/properties
- Deduplicated some code
- Should also fix the issue with #65
Next Steps (Once this gets merged I will):
- try to get the code coverage to be higher by adding more tests.
- Look into adding mocked tests on top of the tests we have with real data
> small refactor

- app/fetchers/playlist.js
- app/helper.js
- app/youtube-grabber.js
I believe youtube may be testing out A/B testing so the code will handle the two different ways they've done it in the past few days
closes #70
> fix parsing error #70

- app/helper.js
- test/channelVideos.test.js
add length seconds & duration text for YouTube Shorts
> extract lengthSeconds for YouTube Shorts

- app/helper.js
- package-lock.json
- test/channelInfo.test.js
This allows length to be properly parsed from shorts.
Without this change: shorts that were uploaded minutes or seconds would cause an error as well as would cause errors when using from certain regions (ex: some ips for other countries would return data that was not in english so the regex would fail)
> fix shorts regex + fix broken test

- package-lock.json
- package.json
Peer dependencies changes
- eslint-config-prettier requires 'prettier'
- another package requires 'eslint-plugin-n'
- eslint-plugin-standard no longer necessary since v16 of eslint-config-standard 16
> update dependencies, add missing peer dependencies

- README.md
- app/fetchers/playlist.js
- app/helper.js
- app/youtube-grabber.js
- index.d.ts
- test/channelHome.test.js
- test/channelInfo.test.js
- test/channelPlaylists.test.js
- test/channelStats.test.js
- test/channelVideos.test.js
- test/communityPosts.test.js
- test/searchChannel.test.js
> Don't error when tabs are missing

- app/helper.js
FreeTubeApp/FreeTube#2784
The YT page that channel videos are extracted from has changed its layout, and this is causing `parseChannelVideoResponse` to not return any videos. Also, the community tab isn't always the 4th tab anymore, and this can cause errors. This PR aims to fix these things by updating the way that page is parsed.
_before:_
_after:_
I assume this layout change was A-B tested because these issues occurred sporadically until recently. 
Some users in the freetube matrix channel had discussed how they were able to change their backend preference to Invidious in order to solve this issue, but it seems that this issue is also effecting Invidious now (EX: https://invidious.namazso.eu/channel/UCXuqSBlHAE6Xw-yeJA0Tunw doesn't display any videos).
I ran the automated tests, and …
> Adjust parsing of channel page

- app/helper.js
- app/youtube-grabber.js
Follow-up to FreeTubeApp/yt-channel-info#113
The video titles coming from `richItemRenderer` is missing the `.text` property, and the result is that `videoTitle` is an object instead of a string. Also, the `channelId` and `channelName` seem to have moved in channel continuations, so this PR maps that data in order to prevent `getChannelVideosMore` from throwing.
_before:_
_after:_
> Adjust parsing of channel page continuation
